config/routes.rb
CardsGame::Application.routes.draw do
  get '/games/join' => 'games#join'
  post '/games/join' => 'games#addplayer'
  resources :games
  post '/games/:id/start' => 'games#start', as: :start_game

  resources :players

  root 'static_pages#index'
  resources :cards

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  

  
end

app/models/game.rb
class Game < ActiveRecord::Base
	belongs_to :creator, class_name: "Player"
	has_and_belongs_to_many :players
	has_many :available_cards, dependent: :destroy
	has_many :cards, through: :available_cards

	validates :name, :code, presence: true
	validates :name, uniqueness: true

	before_update :prevent_reactivate
	after_update :setup_game

	private
		def prevent_reactivate
			if closed == false && closed_was == true
				write_attribute(:closed, true)
			end
		end	

		def setup_game
			if closed == true && closed_was == false
			    cards = Card.all
    			cards.each do |card|
      				if card.game.nil? || card.game == id
      					c = AvailableCard.new
      					c.card_id = card.id
      					c.game_id = id
      					c.save    			
    				end
  				end
  			end			
		end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :authorize
  before_action :set_game, only: [:show, :edit, :update, :destroy, :start]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
    @cards = @auth_player.cards.where('game_id = "?"', @game.id)
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  def addplayer
    name = params[:name]
    code = params[:code]
    game = Game.find_by(name: name)
    if !game.nil? and game.code = code
      g = GamesPlayers.new
      g.player_id = @auth_player.id
      g.game_id = game.id
      g.save
      redirect_to game_path(game), notice: "Welcome to the Game!"
    else
      redirect_to "/games/join", notice: "Could not find that game."
    end
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)
    @game.creator_id = @auth_player.id
    @game.game_status = "not_started"
    respond_to do |format|
      if @game.save
        g = GamesPlayers.new
        g.player_id = @auth_player.id
        g.game_id = @game.id
        g.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    cards = CardsPlayer.where("game_id = ?", @game.id)
    cards.destroy_all
    @game.destroy

    respond_to do |format|
      format.html { redirect_to games_url }
    end
  end

  def start
    if @game.game_status == "started"
      redirect_to game_path(@game)
    end

    
    @game.players.each do |player| 
      cards = @game.cards.limit(10).where("cardtype = 'A'").order("RANDOM()")
      cards.each do |card|
        assign = CardsPlayer.new  
        assign.game_id = @game.id
        assign.player_id = player.id
        assign.card_id = card.id
        assign.save
        refcard = AvailableCard.where("game_id = ? and card_id = ?", @game.id, card.id).first
        refcard.destroy
      end
    end
    
    @game.update(game_status: "started")

    redirect_to game_path(@game) 
  end





  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:name, :code, :closed)
    end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :code %><br>
    <%= f.text_field :code %>
  </div>
  
  <div class="field">
    <%= f.label :closed %><br>
    <%= f.check_box :closed %>
  </div>
  <p><b>Note:</b> once the game is closed to new participants, it cannot be reopened.</p>

  

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/_join_form.html.erb
<h3>Join an existing Game</h3>
<%= form_tag '/games/join', class: "form-inline", role: "form"  do %>
  <div class="form-group">  
    <%= label_tag :name, 'Game Name:', class: "sr-only" %>
    <%= text_field_tag :name, params[:name], class: "form-control", placeholder: "Enter game name" %>
  </div>
  <div class="form-group">
    <%= label_tag :code, 'Code:', class: "sr-only" %>
    <%= text_field_tag :code, params[:code], class: "form-control", placeholder: "Enter code provided by game owner" %>
  </div>
  
  <%= submit_tag "Join", class: "btn btn-default" %>
      
  </div>
  <% end %>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<h1>Listing games</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Code</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.name %></td>
        <th><%= game.code %></th>
        <td><%= link_to 'Show', game %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path %>

app/views/games/join.html.erb
<%= render 'join_form' %>

app/views/games/new.html.erb
<h1>New game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @game.name %>
</p>

<p>
  <strong>Code:</strong>
  <%= @game.code %>
</p>


<ul>
	<% @game.players.each do |player| %>
		<li><%= player.name %> (<%= player.email %>)</li>
	<% end %>
</ul>
<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>


	<% if @game.closed && @game.game_status == "not_started" %>
		<%= link_to "Start Game", start_game_path(@game), class: "btn btn-success", method: :post %>
	<% end %>
	<br>
	
	<% if @game.game_status == "started" %>
		<% @cards.each do |card| %>
			<div class="card white pull-left">
				<h3><%= card.text.html_safe %></h3>
			</div>
		<% end %>
	<% end %>
	
	<br>