config/routes.rb
CardsGame::Application.routes.draw do
  get '/games/join' => 'games#join'
  post '/games/join' => 'games#addplayer'
  resources :games
  post '/games/:id/start' => 'games#start', as: :start_game

  resources :players

  root 'static_pages#index'
  resources :cards

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  

  
end

app/models/card.rb
class Card < ActiveRecord::Base
	has_many :available_cards
	has_many :games, through: :available_cards
	has_many :cards_players
	has_many :players, through: :cards_players
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy]

  # GET /cards
  # GET /cards.json
  def index
      @cards = Card.all.paginate(page: params[:page], per_page: 100) 
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
    redirect_to root_path, notice: "You cannot edit this card."
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(card_params)

    respond_to do |format|
      if @card.save
        format.html { redirect_to @card, notice: 'Card was successfully created.' }
        format.json { render action: 'show', status: :created, location: @card }
      else
        format.html { render action: 'new' }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url }
      format.json { head :no_content }
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def card_params
      params.require(:card).permit(:type, :text, :num_answers, :expansion)
    end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_form.html.erb
<%= form_for(@card) do |f| %>
  <% if @card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
      <% @card.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cardtype %><br>
    <%= f.text_field :cardtype %>
  </div>
  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_field :text %>
  </div>
  <div class="field">
    <%= f.label :numAnswers %><br>
    <%= f.text_field :numAnswers %>
  </div>
  <div class="field">
    <%= f.label :expansion %><br>
    <%= f.text_field :expansion %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cards/edit.html.erb
<h1>Editing card</h1>

<%= render 'form' %>

<%= link_to 'Show', @card %> |
<%= link_to 'Back', cards_path %>

app/views/cards/index.html.erb
<h1>Listing cards</h1>

<table>
  <thead>
    <tr>
      <th>Type</th>
      <th>Text</th>
      <th>Num answers</th>
      <th>Expansion</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

<%= will_paginate @properties, renderer: BootstrapPagination::Rails %>
  <tbody>
    <% @cards.each do |card| %>
      <tr>
        <td><%= card.cardtype %></td>
        <td><%= card.text %></td>
        <td><%= card.numAnswers %></td>
        <td><%= card.expansion %></td>
        <td><%= link_to 'Show', card %></td>
        <td><%= link_to 'Edit', edit_card_path(card) %></td>
        <td><%= link_to 'Destroy', card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= will_paginate @properties, renderer: BootstrapPagination::Rails %>
<%= link_to 'New Card', new_card_path %>

app/views/cards/new.html.erb
<h1>New card</h1>

<%= render 'form' %>

<%= link_to 'Back', cards_path %>

app/views/cards/show.html.erb
<div class="panel panel-primary black-card-container">
  <div class="panel-heading">
    <h3 class="panel-title">Current Card</h3>
  </div>
  <div class="panel-body">
    


<% if @card.cardtype == "A" %>
	<div class="card white"> <!-- make it a white card -->
<% else %>
	<div class="card black"> <!-- make it a black card -->
<% end %>



 <h3><%= @card.text %></h3>

<% if @card.cardtype == "Q" %>
<p>
  <strong>Num answers:</strong>
  <%= @card.numAnswers %>
</p>
<% end %>

</div>

  </div>
</div>

<%= link_to 'Back', cards_path %>